---
name: my_bookly
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  easy_splash_screen: ^1.0.4
  google_fonts: ^6.2.0
  go_router: ^13.2.0
  dartz: ^0.10.1
  dio: ^5.4.1
  flutter_bloc: ^8.1.4
  get_it: ^7.6.7
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  redacted: ^1.0.11
  url_launcher: ^6.2.5
  flutter_launcher_icons: ^0.13.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/icon.png"
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  fonts:
  - family: Benne-Regular
    fonts:
    - asset: assets/fonts/Benne-Regular.ttf
